# This file was generated by GoReleaser. DO NOT EDIT.
cask "iron" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_amd64.tar.gz"
      sha256 "50b3ded64f50354ed85bfd0660f7ab88d4753bf7e89b9f87567a2f0ab7d5c6c6"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_arm64.tar.gz"
      sha256 "f67f3fde19539b84ae16d6dbc576fa6934ca1ab91402217846a6060afc62f7b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_amd64.tar.gz"
      sha256 "68b55a8acd746a62e7ac9734947a4b0e08c732fea7cff72fd54f645e0ad21b12"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_arm64.tar.gz"
      sha256 "4f62e96152da4193e80f4aea77f4e5ee5fe8c5a291552dc852c4f55dbea4f7f6"
    end
  end

  name "iron"
  desc "Scaffold production-grade Kubernetes development environments"
  homepage "https://github.com/dag7/ironplate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iron"

  # No zap stanza required

end
