# This file was generated by GoReleaser. DO NOT EDIT.
cask "iron" do
  name "iron"
  desc "Scaffold production-grade Kubernetes development environments"
  homepage "https://github.com/dag7/ironplate"
  version "0.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iron"

  on_macos do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_amd64.tar.gz"
      sha256 "dbee2e0c5799497c8d08dd38e1dc196165fd8926f7ccb8804eefc1a3b3f922ee"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_arm64.tar.gz"
      sha256 "15e15c11d1c69d8b61d03f7fa5ecb5920f2f149e295f0b57edaae2ec9b52631c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_amd64.tar.gz"
      sha256 "49cf0a5c7c05f6750019ebc77400533fd9a89e3bf077bf65d3e840d92e0d28ac"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_arm64.tar.gz"
      sha256 "65f1fc054a88cea7c84caa6560cf602fd35f4f171e6ae42125ebfa05accad12b"
    end
  end

  # No zap stanza required
end
