# This file was generated by GoReleaser. DO NOT EDIT.
cask "iron" do
  name "iron"
  desc "Scaffold production-grade Kubernetes development environments"
  homepage "https://github.com/dag7/ironplate"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iron"

  on_macos do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_amd64.tar.gz"
      sha256 "74c7f6550306acb586c9a2d687ddf24cf90cd285f4094a4bdcbb9e4238abe75f"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_darwin_arm64.tar.gz"
      sha256 "70dd618a05b1bb85a8ba0812c1d74a149bcaaf16d99a3ba8bbe0821aff2c4c54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_amd64.tar.gz"
      sha256 "74fdb3e6062e27cda89f28e739883546f3cc572ce8ecc5fc6bda6e14f13e97f6"
    end
    on_arm do
      url "https://github.com/dag7/ironplate/releases/download/v#{version}/iron_linux_arm64.tar.gz"
      sha256 "c299461dce7d564f98cd343ddf2d1d573140260933bc135186804c4b523feae8"
    end
  end

  # No zap stanza required
end
